version: '3.2'

services:
   db:
      image: mysql:5.6
      container_name: appsDB
      restart: always
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: helloworld
   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin:5.0
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
